### ISSUE TITLE
[Enhancement] Integration with bulkbuy

### ISSUE THREAD

**Issue by Antunes43** [Vladinator/wow-addon-compactvendor#14]
Could you please make it work with bulk buy?

**Comment by Vladinator** [comment]
I can look into it, I recently added support for BuyEmAll.

I did find Bulk Buy on CF but it seems to be a while since it got updates, so I assume by now you or others moved to another variant.

There are many addons that improve the default item count picker dialog so it's difficult to support all, but I agree I could add support for the most popular and used once for convenience.
