### ISSUE TITLE
Timeless Isle vendor broken

### ISSUE THREAD

**Issue by vioray** [Vladinator/wow-addon-compactvendor#22]
the vendor Mistweaver Ai shows an empty inventory when the addon is enabled, even if set to show everything
without the addon she has several items for sale

**Comment by vioray** [comment]
the Warspear vendors of Seal of Tempered Fate are similarly showing empty

**Comment by Vladinator** [comment]
I recently looked at the mentioned vendors and noticed it was due to changes in how tooltips are scanned.

I hope that the latest update fixed this issue, and made the vendors usable again.

(On a side-note, searching will be fixed soon when I update the libraries to a newer version that also supports the tooltip changes.)
